language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean package
  - mvn cobertura:cobertura

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
